import { describe, expect, it } from 'vitest';
import {
  documentationForDay,
  type DayDocumentationRecord,
} from './useCompletedDayRecords';

const record = (
  over: Partial<DayDocumentationRecord> & Pick<DayDocumentationRecord, 'id'>,
): DayDocumentationRecord => ({
  type: 'malfunction',
  dateStr: '2026-08-10',
  technicianId: 'tech-1',
  customerId: null,
  customerName: 'לקוח',
  location: '',
  city: '',
  completionStatus: 'done',
  completionNotes: '',
  scheduledTime: null,
  ...over,
});

describe('documentationForDay', () => {
  it('keeps only the given day', () => {
    const records = [
      record({ id: 'db-malf-a' }),
      record({ id: 'db-malf-b', dateStr: '2026-08-11' }),
    ];
    expect(
      documentationForDay(records, '2026-08-10', 'tech-1', []).map((r) => r.id),
    ).toEqual(['db-malf-a']);
  });

  it('keeps only the selected technician', () => {
    const records = [
      record({ id: 'db-malf-a' }),
      record({ id: 'db-malf-b', technicianId: 'tech-2' }),
      record({ id: 'db-malf-c', technicianId: null }),
    ];
    expect(
      documentationForDay(records, '2026-08-10', 'tech-1', []).map((r) => r.id),
    ).toEqual(['db-malf-a']);
  });

  // A completed job that hasn't been closed yet is BOTH a live board job and a
  // completed row — without this it would render twice on the same day.
  it('drops records whose job is still drawn on the day', () => {
    const records = [record({ id: 'db-malf-a' }), record({ id: 'db-inst-b' })];
    expect(
      documentationForDay(records, '2026-08-10', 'tech-1', ['db-malf-a']).map(
        (r) => r.id,
      ),
    ).toEqual(['db-inst-b']);
  });

  // Synthetic filter ids are deterministic and regenerated by the board every render,
  // so an archived filter record can collide with a freshly generated open job.
  it('drops an archived filter record when the board regenerated the same id', () => {
    const id = 'filter-2026-8-db-cust-42';
    const records = [record({ id, type: 'filter_replacement' })];
    expect(documentationForDay(records, '2026-08-10', 'tech-1', [id])).toEqual(
      [],
    );
  });

  it('accepts a Set of live ids as well as an array', () => {
    const records = [record({ id: 'db-malf-a' })];
    expect(
      documentationForDay(records, '2026-08-10', 'tech-1', new Set(['db-malf-a'])),
    ).toEqual([]);
  });
});
